# Generated by Django 5.0.6 on 2024-06-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ped',
        ),
    ]
