# Generated by Django 5.0.4 on 2024-06-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_delete_ped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='La direccion'),
        ),
    ]
